[[language]]
name = "c"
scope = "source.c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "latex"
scope = "source.tex"
file-types = ["tex"]
formatter = { command = "latexindent", args = ["-"] }
auto-format = true
